server:
  port: 8013

spring:
  profiles: 
    active: local
  application:
    name: wms-mq

rocketmq: 
 groupName: please_rename_unique_group_name #发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
 isEnable: true #是否开启自动配置
 namesrvAddr: 192.168.80.133:9876 #mq的nameserver地址
 producer: 
  maxMessageSize: 4096 #消息最大长度 默认1024*4(4M)
  sendMsgTimeout: 3000 #发送消息超时时间,默认3000
  retryTimesWhenSendFailed: 2 #发送消息失败重试次数，默认2
 consumer:
   consumeThreadMin: 5 #消费者线程数量
   consumeThreadMax: 32
   consumeMessageBatchMaxSize: 1 #设置一次消费消息的条数，默认为1条
