spring:
  datasource:
    url: jdbc:mysql://rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com:3306/newsaas
    username: root_top
    password: root_Top
    driver-class-name: com.mysql.cj.jdbc.Driver
    
avatar: 
 encode: UTF-8
 schema: newsaas
 domainName: com.zlsrj.wms
 projectName: saas
 projectNameApi: api
 projectNameWeb: admin
 projectNameFlyway: flyway
 projectNameVue: wms-admin-web
 artifactId: wms-saas
 artifactIdApi: wms-api
 artifactIdWeb: wms-admin
 artifactIdFlyway: wms-flyway
 author: wms
 target: 
  dir: D:/spaceWms/wms-cloud
  dirVue: D:/avatarVue
  dirBak: D:/avatarBak
 template: 
  dir: D:/spaceWms/wms-cloud/wms-generator/src/main/resources/templates/saas
 tomcat: 
  port: 8080
 database: 
  ip: rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com
  port: 3306
  schema: newsaas
  username: root_top
  password: root_Top  