spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wop
    username: root
    password: Abc123#$%123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
avatar: 
 encode: UTF-8
 schema: wop
 domainName: com.zlsrj.wms
 projectName: module
 projectNameApi: api
 projectNameWeb: admin
 projectNameVue: wms-admin-web
 artifactId: wms-module
 artifactIdApi: wms-api
 artifactIdWeb: wms-admin
 author: wms
 target: 
  dir: D:/spaceWms/wms-cloud
  dirVue: D:/avatarVue
  dirBak: D:/avatarBak
 template: 
  dir: D:/spaceWms/wms-cloud/wms-generator/src/main/resources/templates/module
 tomcat: 
  port: 8080
 database: 
  ip: localhost
  port: 3306
  schema: wop
  username: root
  password: Abc123#$%123  