server:
  port: 8007

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: wms-dev-8007
    prefer-ip-address: true

spring:
  application:
    name: wms-dev
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/wiot
    username: root
    password: Abc123#$%123
  boot:
    admin:
      client:
        url: "http://localhost:7080"
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.abc.zlsrj.wms.dev: debug


id: 
  config: 
    workerId: 24 #最大支持机器节点数0~31，一共32个
    datacenterId: 24 #最大支持数据中心节点数0~31，一共32个