eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.blogiscapital.cn/eureka

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.148.213:3306/wop
    username: root
    password: Abc123#$%123
  redis:
    database: 0
    host: 192.168.148.214
    port: 6379
    password: Abc123#$%123
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  activemq:
    broker-url: tcp://activemq.blogiscapital.cn:61616
    user: admin
    password: admin