eureka:
  client:
    service-url:
      defaultZone: http://eureka/eureka

spring:
  datasource:
   driver-class-name: com.p6spy.engine.spy.P6SpyDriver
   url: jdbc:p6spy:mysql://rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com:3306/newsaas
   username: root_top
   password: root_Top