eureka:
  client:
    service-url:
      defaultZone: http://eureka:7001/eureka

spring:
  datasource:
   driver-class-name: com.p6spy.engine.spy.P6SpyDriver
   url: jdbc:p6spy:mysql://mysql:3306/newsaas
   username: root
   password: 123456