server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: wms-id-8001
    prefer-ip-address: true

spring:
  application:
    name: wms-id
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/wop
    username: root
    password: 123456

id: 
  config: 
    workerId: 1
    datacenterId: 2
    
