server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: wms-system-8004
    prefer-ip-address: true


spring:
  application:
    name: wms-system
  profiles: 
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wop
    username: root
    password: 123456
  boot:
    admin:
      client:
        url: "http://localhost:7080"
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false=Queue true=Topic

management:
  endpoints:
    web:
      exposure:
        include: "*"
# Logger Config
logging:
  level:
    com.abc.zlsrj.wms.system: debug

id: 
  config: 
    workerId: 18 #最大支持机器节点数0~31，一共32个
    datacenterId: 18 #最大支持数据中心节点数0~31，一共32个