# DataSource Config
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/wop
    username: root
    password: 123456


# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
