spring:
  profiles: 
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wop
    username: root
    password: 123456
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false=Queue true=Topic
# Logger Config
logging:
  level:
    com.abc.springboot2.mybatisplus.generator: debug

    
mq:
  mbg: 
    tenant: 
      custType: mq-mbg-tenant-custType
      waterType: mq-mbg-tenant-waterType
      system: mq-mbg-tenant-system