server:
  port: 7090

  
spring:
  flyway:
    baseline-version: 1.0.0
    enabled: false
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    baseline-on-migrate: true
  datasource:
    url: jdbc:mysql://localhost:3306/flyway_his
    username: root
    password: Abc123#$%123
    driver-class-name: com.mysql.cj.jdbc.Driver