server:
  port: 8009

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: wms-employee-8009
    prefer-ip-address: true

spring:
  profiles: 
    active: local
  application:
    name: wms-employee
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/wop
    username: root
    password: Abc123#$%123
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: redis2019
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  boot:
    admin:
      client:
        url: "http://localhost:7080"
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
  jms:
    pub-sub-domain: false # false=Queue true=Topic
    
mq:
  mbg: 
    tenant: 
      rbac: mq-mbg-tenant-rbac
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.abc.zlsrj.wms.employee: debug


id: 
  config: 
    workerId: 28 #最大支持机器节点数0~31，一共32个
    datacenterId: 28 #最大支持数据中心节点数0~31，一共32个