eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.blogiscapital.cn/eureka

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.148.213:3306/wop
    username: root
    password: Abc123#$%123
