spring:
  datasource: 
   driver-class-name: com.p6spy.engine.spy.P6SpyDriver
   url: jdbc:p6spy:mysql://rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com:3306/guiyuandb
   username: root
   password: ENC(DNsJoa9UB5/WCdU2k946tQ==)

eureka:
  client:
    service-url:
      defaultZone: http://eureka:7001/eureka
