server:
  port: 9001

spring:
  application:
    name: wms-admin
  datasource: 
    url: jdbc:mysql://localhost:3306/wop
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false

feign:
  hystrix:
    enabled: false