server:
  port: 9001

spring:
  profiles: 
    active: local
  application:
    name: wms-admin
  datasource: 
    url: jdbc:mysql://localhost:3306/wop
    username: root
    password: ENC(uQlNcXwafbkFVHVbLnVihVnv/RK4nz55)
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false

feign:
  hystrix:
    enabled: false
  httpclient:
    enabled: true #Feign默认使用的连接工具实现类，所以里面发现只要你有body体对象，就会强制的把GET请求转换成POST请求

jwt: 
  secret: mySecret
  expiration: 604800 #60*60*24
  tokenHeader: Authorization
  tokenHead: Bearer
  
jasypt: 
 encryptor: 
  password: guiyuan2020