spring:
  datasource: 
    url: jdbc:mysql://192.168.148.213:3306/wop
    username: root
    password: Abc123#$%123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.blogiscapital.cn/eureka
