spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/wop
    username: root
    password: ENC(uQlNcXwafbkFVHVbLnVihVnv/RK4nz55)
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
