server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: wms-saas-8011
    prefer-ip-address: true

spring:
  profiles: 
    active: local
  application:
    name: wms-saas
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com:3306/root_top
    username: root
    password: ENC(DqlW5ueDybAoWWQSoPGwX9Qq1SQfERao)
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ENC(nWhJhvxwofclqYT0wHmtLljFaoabGEkg)
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
  boot:
    admin:
      client:
        url: "http://localhost:7080"
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.abc.zlsrj.wms.saas: debug


id: 
  config: 
    workerId: 26 #最大支持机器节点数0~31，一共32个
    datacenterId: 26 #最大支持数据中心节点数0~31，一共32个
    
jasypt: 
 encryptor: 
  password: guiyuan2020
  
  
#系统配置员工密码生成规则
#defaultPasswordStrategy 默认模式，手机号码后6位
#randomPasswordStrategy  随机生成6位数字
system: 
 config: 
  password: 
   mode: defaultPasswordStrategy
  