eureka:
  client:
    service-url:
      defaultZone: http://39.100.108.49:7001/eureka

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com:3306/guiyuandb
    username: root_top
    password: ENC(DqlW5ueDybAoWWQSoPGwX9Qq1SQfERao)
  boot:
    admin:
      client:
        url: "http://39.100.108.49:7080"