eureka:
  client:
    service-url:
      defaultZone: http://39.100.108.49:7001/eureka

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://rm-uf6k42ke05jq7358so.mysql.rds.aliyuncs.com:3306/guiyuandb
    username: root_top
    password: ENC(DqlW5ueDybAoWWQSoPGwX9Qq1SQfERao)
  redis:
    database: 0
    host: 172.26.2.97
    port: 6379
    password: ENC(SPym8Q9KkAafCAEkjLA2I/i666yIsGJo)
    jedis:
      pool:
        max-active: 64
        max-wait: -1
        max-idle: 32
        min-idle: 0
    timeout: 10000
  boot:
    admin:
      client:
        url: "http://39.100.108.49:7080"